Custom exception class
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject\hotel.py", line 20, in wrapper
    func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\pythonProject\manager\hotel_manager.py", line 59, in zip_with_do_something_results
    raise CustomException
exception.CustomException: Custom exception class
ERROR:hotel:Custom exception class
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\pythonProject\hotel.py", line 20, in wrapper
    func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\pythonProject\manager\hotel_manager.py", line 59, in zip_with_do_something_results
    raise CustomException
exception.CustomException: Custom exception class
